dim swApp
dim storePath
dim docVisible
#If VBA7 Then
Private Type BROWSEINFO
   hwndOwner       As LongPtr
   pIDLRoot        As Long
   pszDisplayName  As String
   lpszTitle       As String
   ulFlags         As Long
   lpfnCallback    As LongPtr
   lParam          As LongPtr
  iImage          As Long
End Type
Private Declare PtrSafe Function SHBrowseForFolder Lib "Shell32" (lpbi As BROWSEINFO) As Long
Private Declare PtrSafe Function SHGetPathFromIDList Lib "Shell32" (ByVal pidList As Long, ByVal lpBuffer As String) As Long
Private Declare PtrSafe Sub CoTaskMemFree Lib "ole32" (ByVal hMem As Long)
#Else
Private Type BROWSEINFO
   hwndOwner       As Long
   pIDLRoot        As Long
   pszDisplayName  As Long
   lpszTitle       As String
   ulFlags         As Long
   lpfnCallback    As Long
   lParam          As Long
  iImage          As Long
End Type
Private Declare Function SHBrowseForFolder Lib "Shell32" (lpbi As BROWSEINFO) As Long
Private Declare Function SHGetPathFromIDList Lib "Shell32" (ByVal pidList As Long, ByVal lpBuffer As String) As Long
Private Declare Sub CoTaskMemFree Lib "ole32" (ByVal hMem As Long)
#End If
Private Const MAX_PATH = 260
'Directories only
Private Const BIF_RETURNONLYFSDIRS = &H1&
'Windows 2000 (Shell32.dll 5.0) extended dialog
Private Const BIF_NEWDIALOGSTYLE = &H40
' show edit box
Private Const BIF_EDITBOX = &H10&
Function getLastFeatureByType(model,typ)  
  Set feat = model.FirstFeature ' Get the 1st feature in part
  Set res = Nothing
  Count = 0
  Do While Not feat Is Nothing ' While we have a valid feature
    If feat.GetTypeName() = typ Then
      Set res = feat
    End If
    Set feat = feat.GetNextFeature() ' Get the next feature
  Loop ' Continue until no more
  Set getLastFeatureByType = res
End Function
' this code with copy a matrix to a other
Function copyMat4x4(source)
Dim res(0 To 15) As Double
For i = 0 To 15
 res(i) = source(i)
Next
copyMat4x4 = res
End Function

' This code creates a mat from a sw mat
Function createMatFromSWMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = 0
 res(4) = source(3)
 res(5) = source(4)
 res(6) = source(5)
 res(7) = 0
 res(8) = source(6)
 res(9) = source(7)
 res(10) = source(8)
 res(11) = 0
 res(12) = source(9)
 res(13) = source(10)
 res(14) = source(11)
 res(15) = source(12)
 createMatFromSWMat = res
End Function
Function createSWMatFromMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = source(4)
 res(4) = source(5)
 res(5) = source(6)
 res(6) = source(8)
 res(7) = source(9)
 res(8) = source(10)
 res(9) = source(12)
 res(10) = source(13)
 res(11) = source(14)
 res(12) = source(15)
 res(13) = 0
 res(14) = 0
 res(15) = 0
 createSWMatFromMat = res
End Function
Function createMat4x4FromValues(x1,x2,x3,y1,y2,y3,z1,z2,z3,t1,t2,t3)
 Dim res(0 To 15) As Double
 res(0) = x1
 res(1) = x2
 res(2) = x3
 res(3) = 0
 res(4) = y1
 res(5) = y2
 res(6) = y3
 res(7) = 0
 res(8) = z1
 res(9) = z2
 res(10) =z3
 res(11) = 0
 res(12) = t1
 res(13) = t2
 res(14) = t3
 res(15) = 1
 createMat4x4FromValues = res
End Function
' this code will mult a common mat with any other stuff
Function multMatMat(ld, xld, yld, rd, xrd, yrd)
  mulRes = yld * xrd
  'Dim od(0 To 0) As Variant
  ReDim od(mulRes - 1) As Double
  For i = 0 To mulRes - 1
   od(i) = 0#
  Next
  y = 0
  While y < yld
    x = 0
    While x < xrd
      i = 0
      While i < xld
       od(x * yld + y) = od(x * yld + y) + ld(i * yld + y) * rd(x * yrd + i)
       i = i + 1
      Wend
      x = x + 1
    Wend
    y = y + 1
  Wend
  multMatMat = od

End Function
' this code will mult a vector with a matrix
Function mulMat4x4Values3d(mat, x,y,z)
  tmp = createVec4d(x, y, z, 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Values3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Vec3d(mat, vec)
  tmp = createVec4d(vec(0), vec(1), vec(2), 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Vec3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Mat4x4(mat1, mat2)
  mulMat4x4Mat4x4 = multMatMat(mat1, 4, 4, mat2, 4, 4)
End Function
' create a 4x4 matrix
Function createMat4x4()
 Dim res(0 To 15) As Double
 for i = 0 to 15 
 res(i) = 0
 next
 createMat4x4 = res
End Function
Function createMat4x4Ident()
 Dim res(0 To 15) As Double
 res(0) = 1
 res(5) = 1
 res(10) = 1
 res(15) = 1
 res(1) = 0
 res(2) = 0
 res(3) = 0
 res(4) = 0
 res(6) = 0
 res(7) = 0
 res(8) = 0
 res(9) = 0
 res(11) = 0
 res(12) = 0
 res(13) = 0
 res(14) = 0
 createMat4x4Ident = res
End Function
' this function create a new vector
Function createVec3d(x, y, z)
 Dim res(0 To 2) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 createVec3d = res
End Function
' this function create a new vector
Function createVec4d(x, y, z, w)
 Dim res(0 To 3) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 res(3) = w
 createVec4d = res
End Function

Function getMatTVec(mat)
 getMatTVec = createVec3d(mat(12), mat(13), mat(14))
End Function

Sub setMatTVec(mat, v)
 mat(12) = v(0)
 mat(13) = v(1)
 mat(14) = v(2)
End Sub
Sub setMatXVec(mat, v)
 mat(0) = v(0)
 mat(1) = v(1)
 mat(2) = v(2)
End Sub
Sub setMatYVec(mat, v)
 mat(4) = v(0)
 mat(5) = v(1)
 mat(6) = v(2)
End Sub
Sub setMatZVec(mat, v)
 mat(8) = v(0)
 mat(9) = v(1)
 mat(10) = v(2)
End Sub
Sub setMatScale(mat, s)
 mat(15) = s
End Sub
Function getMatXVec(mat)
 getMatXVec = createVec3d(mat(0), mat(1), mat(2))
End Function
Function getMatYVec(mat)
 getMatYVec = createVec3d(mat(4), mat(5), mat(6))
End Function
Function getMatZVec(mat)
 getMatZVec = createVec3d(mat(8), mat(9), mat(10))
End Function

Function negVec3d(v)
 negVec3d = createVec3d(-v(0), -v(1), -v(2))
End Function
Function scaleVec3d(v,s)
 scaleVec3d = createVec3d(v(0)*s,v(1)*s,v(2)*s)
End Function
' invert a 4x4 matrix
Function invMat4x4(source)
target = copyMat4x4(source)
setMatTVec target, createVec3d(0, 0, 0)
 target(1) = source(4)
 target(4) = source(1)
 target(2) = source(8)
 target(8) = source(2)
 target(6) = source(9)
 target(9) = source(6)
 setMatScale target,1
 t = getMatTVec(source)
 v = mulMat4x4Vec3d(target, t)
 setMatTVec target, negVec3d(v)
 invMat4x4 = target
End Function
Function getFaceFromModel(part, pos, normal)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   found = 0
   Dim body As Object
   Set body = partBodies(k)
   Set face = body.GetFirstFace()
   getFaceFromModel = noting
   Do While Not face Is Nothing ' While we have a valid feature
     Set sur = face.GetSurface()
     If sur.IsPlane() Then
       planePara = sur.PlaneParams
       faceNormal = face.normal
       nTest = faceNormal(0) * normal(0) + faceNormal(1) * normal(1) + faceNormal(2) * normal(2)
       If nTest > 1 - 0.000001 Then
         ' check projection
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If dTest < 0.000001 Then
           Set getFaceFromModel = face
           found=1
           Exit Do
         End If
       End If
     else
       If sur.IsCylinder() then
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If dTest < 0.00000001 Then
           res=sur.EvaluateAtPoint(closeRes(0),closeRes(1),closeRes(2))
           nTest=res(0)*normal(0)+res(1)*normal(1)+res(2)*normal(2)
           if nTest>1-0.00000001 then
             Set getFaceFromModel = face
             found=1
             Exit Do
           End if
         End if
       End if
     End if
     Set face = face.GetNextFace ' Get the next Face
   Loop
   If (found = 1) Then
     Exit For
   End If
 Next k
End Function
Function getEdgeFromModel(part, pos,byref edgeRet)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   Dim body As Object
   Set body = partBodies(k)
   edges= body.GetEdges()
   start= LBound(edges)
   ende = UBound(edges)
   For i = start To ende
     Set edge = edges(i)
     closeRes=edge.GetClosestPointOn(pos(0),pos(1),pos(2))
     dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
     If dTest < 0.00000001 Then
       set edgeRet=edge
       getEdgeFromModel=true
       exit function
     End If
   Next i
 Next k
 getEdgeFromModel=false
End Function
sub cLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.SketchManager.CreateLine pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cCLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.CreateCenterLineVB pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cArc(part,wMat,x1,y1,x2,y2,x3,y3)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
pk3=mulMat4x4Values3d(wMat,x3,y3,0)
Part.SketchManager.Create3PointArc pk1(0),pk1(1),0,pk3(0),pk3(1),0,pk2(0),pk2(1),0
end sub
sub cCir(part,wMat,x1,y1,rad)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
Part.SketchManager.CreateCircleByRadius pk1(0),pk1(1),0,rad
end sub
Public Function BrowseForFolder() As String
  Dim tBI         As BROWSEINFO
  Dim lngPIDL     As Long
  Dim strPath     As String
  With tBI
    .lpszTitle = ""
    .ulFlags = BIF_RETURNONLYFSDIRS Or BIF_NEWDIALOGSTYLE Or BIF_EDITBOX
  End With
  lngPIDL = SHBrowseForFolder(tBI)
  If (lngPIDL <> 0) Then
    ' get path from ID list
    strPath = Space$(MAX_PATH)
    SHGetPathFromIDList lngPIDL, strPath
    strPath = Left$(strPath, InStr(strPath, Chr$(0)) - 1)
    ' release list
    CoTaskMemFree lngPIDL
  End If
  BrowseForFolder = strPath
End Function
Sub CreatePart0
dim errors as long
dim warnings as long
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set res=swApp.OpenDoc6 ( storePath & "529027 SDE5-Q4-K(FP)---(DS).sldprt",1,3,"", errors, warnings)
if not res is nothing then
 if (docVisible=0) then
  swApp.DocumentVisible 1, 1
 end if
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
Dim longstatus As Long
Dim sPartTemplateName As String
sPartTemplateName = swApp.GetUserPreferenceStringValue(8)
Set part = swApp.NewDocument(sPartTemplateName, 0, 0, 0)
swApp.ActivateDoc2 "529027 SDE5-Q4-K(FP)---(DS).sldprt", False, longstatus
Set part = swApp.ActiveDoc
part.SketchManager.AddToDB = true
part.SketchManager.DisplayWhenAdded = false
part.ActiveView.EnableGraphicsUpdate = false
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NN", 30, "SDE5-(DS)"
customPropMgr.Add2 "NT", 30, "Pressure sensors - Housing"
customPropMgr.Add2 "NB", 30, "529027 SDE5-Q4-K(FP)---(DS)"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $TYP.-$PA.-$EAN.($SF.)---(DS)"
customPropMgr.Add2 "LINA", 30, "529027 SDE5-Q4-K(FP)---(DS)"
customPropMgr.Add2 "TNR", 30, "529027"
customPropMgr.Add2 "TYP", 30, "SDE5"
customPropMgr.Add2 "SF", 30, "FP"
customPropMgr.Add2 "PA", 30, "Q4"
customPropMgr.Add2 "EAN", 30, "K"
customPropMgr.Add2 "EA", 30, "P"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "529027 SDE5-Q4-K(FP)---(DS)"
customPropMgr.Add2 "BOMINFO", 30, "529027 SDE5-Q4-K(FP)---(DS)"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
customPropMgr.Add2 "IsFastener", 30, "0"
part.SummaryInfo(0)="529027 SDE5-Q4-K(FP)---(DS)"
part.SummaryInfo(4)="Pressure sensors - Housing"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.31000000238419
valRGB(1)=0.31000000238419
valRGB(2)=0.31000000238419
part.MaterialPropertyValues=valRGB
Dim featMgr as object
set featMgr = part.FeatureManager
codeBag0 part,featMgr
codeBag15 part,featMgr
part.ActiveView.EnableGraphicsUpdate = true
part.SketchManager.DisplayWhenAdded = true
part.SketchManager.AddToDB = false
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "529027 SDE5-Q4-K(FP)---(DS).sldprt",0,0,nothing,errors,warnings
End Sub
Sub CreatePart1
dim errors as long
dim warnings as long
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set res=swApp.OpenDoc6 ( storePath & "653056 SDE5---(H).sldprt",1,3,"", errors, warnings)
if not res is nothing then
 if (docVisible=0) then
  swApp.DocumentVisible 1, 1
 end if
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
Dim longstatus As Long
Dim sPartTemplateName As String
sPartTemplateName = swApp.GetUserPreferenceStringValue(8)
Set part = swApp.NewDocument(sPartTemplateName, 0, 0, 0)
swApp.ActivateDoc2 "653056 SDE5---(H).sldprt", False, longstatus
Set part = swApp.ActiveDoc
part.SketchManager.AddToDB = true
part.SketchManager.DisplayWhenAdded = false
part.ActiveView.EnableGraphicsUpdate = false
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NN", 30, "SDE5-(H)"
customPropMgr.Add2 "NT", 30, "Pressure sensors - Holder"
customPropMgr.Add2 "NB", 30, "653056 SDE5---(H)"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $TYP.---(H)"
customPropMgr.Add2 "LINA", 30, "653056 SDE5---(H)"
customPropMgr.Add2 "TNR", 30, "653056"
customPropMgr.Add2 "TYP", 30, "SDE5"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "653056 SDE5---(H)"
customPropMgr.Add2 "BOMINFO", 30, "653056 SDE5---(H)"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
customPropMgr.Add2 "IsFastener", 30, "0"
part.SummaryInfo(0)="653056 SDE5---(H)"
part.SummaryInfo(4)="Pressure sensors - Holder"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.31000000238419
valRGB(1)=0.31000000238419
valRGB(2)=0.31000000238419
part.MaterialPropertyValues=valRGB
Dim featMgr as object
set featMgr = part.FeatureManager
codeBag25 part,featMgr
codeBag40 part,featMgr
part.ActiveView.EnableGraphicsUpdate = true
part.SketchManager.DisplayWhenAdded = true
part.SketchManager.AddToDB = false
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "653056 SDE5---(H).sldprt",0,0,nothing,errors,warnings
End Sub
sub CreatePart2
dim errors as long
dim warnings as long
set res=swApp.OpenDoc6 ( storePath & "529027 SDE5-D10-FP-Q4-P-K---(asm).sldasm",2,3,"", errors, warnings)
if not res is nothing then
 exit sub
end if
createPart0
createPart1
set part=swApp.NewAssembly
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NN", 30, "SDE5 (m)"
customPropMgr.Add2 "NT", 30, "Drucksensor, Baukasten"
customPropMgr.Add2 "NB", 30, "529027 SDE5-D10-FP-Q4-P-K---(asm)"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $TYP.-$DB.$DET.-$SF.-$PA.-$EA.-$EAN.$AKT.$WSEX2.$WSEY2.---(asm)"
customPropMgr.Add2 "LINA", 30, "529027 SDE5-D10-FP-Q4-P-K"
customPropMgr.Add2 "TNR", 30, "529027"
customPropMgr.Add2 "TYP", 30, "SDE5"
customPropMgr.Add2 "DB", 30, "D10"
customPropMgr.Add2 "DE", 30, "-"
customPropMgr.Add2 "SF", 30, "FP"
customPropMgr.Add2 "PA", 30, "Q4"
customPropMgr.Add2 "EA", 30, "P"
customPropMgr.Add2 "EAN", 30, "K"
customPropMgr.Add2 "AK", 30, "-"
customPropMgr.Add2 "WSEX", 30, "0.000"
customPropMgr.Add2 "WSEY", 30, "0.000"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "529027 SDE5-D10-FP-Q4-P-K---(asm)"
customPropMgr.Add2 "BOMINFO", 30, "529027 SDE5-D10-FP-Q4-P-K"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
part.SummaryInfo(0)="529027 SDE5-D10-FP-Q4-P-K"
part.SummaryInfo(4)="Drucksensor, Baukasten"
part.SummaryInfo(2)="Cadenas PARTsolutions"
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set comp = part.AddComponent5 (storePath &"529027 SDE5-Q4-K(FP)---(DS).sldprt", 0, "", false, "",0,0,0)
posMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp = part.AddComponent5 (storePath &"653056 SDE5---(H).sldprt", 0, "", false, "",0,0,0)
posMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,-0.006,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
swApp.CloseDoc storePath &"529027 SDE5-Q4-K(FP)---(DS).sldprt"
swApp.CloseDoc storePath &"653056 SDE5---(H).sldprt"
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "529027 SDE5-D10-FP-Q4-P-K---(asm).sldasm",0,0,nothing,errors,warnings
end sub
sub codeBag1(part,wMat)
cArc part,wMat,-0.008,0.008,-1.4695761589768e-18,0,0.008,0.008
cLn part,wMat,0.008,0.008,0.008,0.02264944167961
cArc part,wMat,0.008,0.02264944167961,0.0079106149670467,0.022934740380689,0.0076744186046512,0.023118033346578
cArc part,wMat,0.0076744186046512,0.023118033346578,1.3471114790621e-18,0.0245,-0.0076744186046512,0.023118033346578
cArc part,wMat,-0.0076744186046512,0.023118033346578,-0.0079106149670467,0.022934740380689,-0.008,0.02264944167961
cLn part,wMat,-0.008,0.02264944167961,-0.008,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag2(part,wMat)
cLn part,wMat,0,0.018,-4.8985871965894e-19,0.008
cLn part,wMat,-4.8985871965894e-19,0.008,0.01875,0.008
cArc part,wMat,0.01875,0.008,0.019103553390593,0.0078535533905933,0.01925,0.0075
cLn part,wMat,0.01925,0.0075,0.01925,-0.0075
cArc part,wMat,0.01925,-0.0075,0.019103553390593,-0.0078535533905933,0.01875,-0.008
cLn part,wMat,0.01875,-0.008,0,-0.008
cLn part,wMat,0,-0.008,1.1021821192326e-18,-0.018
cLn part,wMat,1.1021821192326e-18,-0.018,0.02925,-0.018
cLn part,wMat,0.02925,-0.018,0.02925,0.018
cLn part,wMat,0.02925,0.018,0,0.018
Part.SketchManager.InsertSketch True
end sub

sub codeBag3(part,wMat)
cLn part,wMat,-0.02925,0.018,-0.02925,-0.018
cLn part,wMat,-0.02925,-0.018,0,-0.018
cLn part,wMat,0,-0.018,4.8985871965894e-19,-0.008
cLn part,wMat,4.8985871965894e-19,-0.008,-0.01875,-0.008
cArc part,wMat,-0.01875,-0.008,-0.019103553390593,-0.0078535533905933,-0.01925,-0.0075
cLn part,wMat,-0.01925,-0.0075,-0.01925,0.0075
cArc part,wMat,-0.01925,0.0075,-0.019103553390593,0.0078535533905933,-0.01875,0.008
cLn part,wMat,-0.01875,0.008,0,0.008
cLn part,wMat,0,0.008,-1.1021821192326e-18,0.018
cLn part,wMat,-1.1021821192326e-18,0.018,-0.02925,0.018
Part.SketchManager.InsertSketch True
end sub

sub codeBag4(part,wMat)
cLn part,wMat,-0.025,0.003,-0.025,-0.0050033769468987
cLn part,wMat,-0.025,-0.0050033769468987,-0.014,-0.0050033769468987
cLn part,wMat,-0.014,-0.0050033769468987,-0.014,0
cLn part,wMat,-0.014,0,-0.01875,0
cArc part,wMat,-0.01875,0,-0.019103553390593,0.00014644660940673,-0.01925,0.0005
cLn part,wMat,-0.01925,0.0005,-0.01925,0.003
cLn part,wMat,-0.01925,0.003,-0.025,0.003
cCLn part,wMat,-0.002,0.008,0.002,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag5(part,wMat)
cLn part,wMat,0.014,-0.0050033769468987,0.025,-0.0050033769468987
cLn part,wMat,0.025,-0.0050033769468987,0.025,0.003
cLn part,wMat,0.025,0.003,0.01925,0.003
cLn part,wMat,0.01925,0.003,0.01925,0.0005
cArc part,wMat,0.01925,0.0005,0.019103553390593,0.00014644660940673,0.01875,0
cLn part,wMat,0.01875,0,0.014,0
cLn part,wMat,0.014,0,0.014,-0.0050033769468987
cCLn part,wMat,-0.002,0.008,0.002,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag6(part,wMat)
cLn part,wMat,-0.02425,0.0295,-0.02425,0.0225
cLn part,wMat,-0.02425,0.0225,-0.01925,0.0225
cLn part,wMat,-0.01925,0.0225,-0.01925,0.024
cArc part,wMat,-0.01925,0.024,-0.019103553390593,0.024353553390593,-0.01875,0.0245
cLn part,wMat,-0.01875,0.0245,-0.01875,0.0295
cLn part,wMat,-0.01875,0.0295,-0.02425,0.0295
cCLn part,wMat,-0.01925,0.0025,-0.02425,0.0025
Part.SketchManager.InsertSketch True
end sub

sub codeBag7(part,wMat)
cArc part,wMat,0.01875,0.0245,0.019103553390593,0.024353553390593,0.01925,0.024
cLn part,wMat,0.01925,0.024,0.01925,0.0225
cLn part,wMat,0.01925,0.0225,0.02425,0.0225
cLn part,wMat,0.02425,0.0225,0.02425,0.0295
cLn part,wMat,0.02425,0.0295,0.01875,0.0295
cLn part,wMat,0.01875,0.0295,0.01875,0.0245
cCLn part,wMat,0.02425,0.0025,0.01925,0.0025
Part.SketchManager.InsertSketch True
end sub

sub codeBag8(part,wMat)
cLn part,wMat,-0.01,0.017,-0.01,0.01
cLn part,wMat,-0.01,0.01,-0.008,0.01
cLn part,wMat,-0.008,0.01,-0.008,0.012016336506011
cArc part,wMat,-0.008,0.012016336506011,-0.0078966766701456,0.012320717220515,-0.0076294095225513,0.012499299419155
cLn part,wMat,-0.0076294095225513,0.012499299419155,-0.0064223542864692,0.012822728894883
cArc part,wMat,-0.0064223542864692,0.012822728894883,-0.0062619939979126,0.012929878214067,-0.0062,0.01311250664277
cLn part,wMat,-0.0062,0.01311250664277,-0.0062,0.01488749335723
cArc part,wMat,-0.0062,0.01488749335723,-0.0062619939979126,0.015070121785933,-0.0064223542864692,0.015177271105117
cLn part,wMat,-0.0064223542864692,0.015177271105117,-0.0076294095225513,0.015500700580845
cArc part,wMat,-0.0076294095225513,0.015500700580845,-0.0078966766701456,0.015679282779485,-0.008,0.015983663493989
cLn part,wMat,-0.008,0.015983663493989,-0.008,0.017
cLn part,wMat,-0.008,0.017,-0.01,0.017
Part.SketchManager.InsertSketch True
end sub

sub codeBag9(part,wMat)
cLn part,wMat,0.0062,0.01488749335723,0.0062,0.01311250664277
cArc part,wMat,0.0062,0.01311250664277,0.0062619939979126,0.012929878214067,0.0064223542864692,0.012822728894883
cLn part,wMat,0.0064223542864692,0.012822728894883,0.0076294095225513,0.012499299419155
cArc part,wMat,0.0076294095225513,0.012499299419155,0.0078966766701456,0.012320717220515,0.008,0.012016336506011
cLn part,wMat,0.008,0.012016336506011,0.008,0.01
cLn part,wMat,0.008,0.01,0.01,0.01
cLn part,wMat,0.01,0.01,0.01,0.017
cLn part,wMat,0.01,0.017,0.008,0.017
cLn part,wMat,0.008,0.017,0.008,0.015983663493989
cArc part,wMat,0.008,0.015983663493989,0.0078966766701456,0.015679282779485,0.0076294095225513,0.015500700580845
cLn part,wMat,0.0076294095225513,0.015500700580845,0.0064223542864692,0.015177271105117
cArc part,wMat,0.0064223542864692,0.015177271105117,0.0062619939979126,0.015070121785933,0.0062,0.01488749335723
Part.SketchManager.InsertSketch True
end sub

sub codeBag10(part,wMat)
cLn part,wMat,-0.01,0.017,-0.01,0.01
cLn part,wMat,-0.01,0.01,-0.008,0.01
cLn part,wMat,-0.008,0.01,-0.008,0.012016336506011
cArc part,wMat,-0.008,0.012016336506011,-0.0078966766701456,0.012320717220515,-0.0076294095225513,0.012499299419155
cLn part,wMat,-0.0076294095225513,0.012499299419155,-0.0064223542864692,0.012822728894883
cArc part,wMat,-0.0064223542864692,0.012822728894883,-0.0062619939979126,0.012929878214067,-0.0062,0.01311250664277
cLn part,wMat,-0.0062,0.01311250664277,-0.0062,0.01488749335723
cArc part,wMat,-0.0062,0.01488749335723,-0.0062619939979126,0.015070121785933,-0.0064223542864692,0.015177271105117
cLn part,wMat,-0.0064223542864692,0.015177271105117,-0.0076294095225513,0.015500700580845
cArc part,wMat,-0.0076294095225513,0.015500700580845,-0.0078966766701456,0.015679282779485,-0.008,0.015983663493989
cLn part,wMat,-0.008,0.015983663493989,-0.008,0.017
cLn part,wMat,-0.008,0.017,-0.01,0.017
Part.SketchManager.InsertSketch True
end sub

sub codeBag11(part,wMat)
cLn part,wMat,0.0062,0.01488749335723,0.0062,0.01311250664277
cArc part,wMat,0.0062,0.01311250664277,0.0062619939979126,0.012929878214067,0.0064223542864692,0.012822728894883
cLn part,wMat,0.0064223542864692,0.012822728894883,0.0076294095225513,0.012499299419155
cArc part,wMat,0.0076294095225513,0.012499299419155,0.0078966766701456,0.012320717220515,0.008,0.012016336506011
cLn part,wMat,0.008,0.012016336506011,0.008,0.01
cLn part,wMat,0.008,0.01,0.01,0.01
cLn part,wMat,0.01,0.01,0.01,0.017
cLn part,wMat,0.01,0.017,0.008,0.017
cLn part,wMat,0.008,0.017,0.008,0.015983663493989
cArc part,wMat,0.008,0.015983663493989,0.0078966766701456,0.015679282779485,0.0076294095225513,0.015500700580845
cLn part,wMat,0.0076294095225513,0.015500700580845,0.0064223542864692,0.015177271105117
cArc part,wMat,0.0064223542864692,0.015177271105117,0.0062619939979126,0.015070121785933,0.0062,0.01488749335723
Part.SketchManager.InsertSketch True
end sub

sub codeBag12(part,wMat)
cArc part,wMat,-0.0085,0.008,-1.5614246689129e-18,-0.0005,0.0085,0.008
cLn part,wMat,0.0085,0.008,0.0085,0.022993901531919
cArc part,wMat,0.0085,0.022993901531919,0.0084128614119224,0.023275939569328,0.0081818181818182,0.023459672021281
cArc part,wMat,0.0081818181818182,0.023459672021281,-3.1728326199867e-18,0.025,-0.0081818181818182,0.023459672021281
cArc part,wMat,-0.0081818181818182,0.023459672021281,-0.0084128614119224,0.023275939569328,-0.0085,0.022993901531919
cLn part,wMat,-0.0085,0.022993901531919,-0.0085,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag13(part,wMat)
cLn part,wMat,0.01925,0.0081,0.02145,0.0081
cLn part,wMat,0.02145,0.0081,0.022202833892775,0.0082346890117618
cArc part,wMat,0.022202833892775,0.0082346890117618,0.022395843330161,0.0083580667076584,0.022445513270952,0.0085816904893691
cLn part,wMat,0.022445513270952,0.0085816904893691,0.02204,0.0109
cLn part,wMat,0.02204,0.0109,0.02065,0.0109
cLn part,wMat,0.02065,0.0109,0.02065,0.0086
cLn part,wMat,0.02065,0.0086,0.01995,0.0086
cLn part,wMat,0.01995,0.0086,0.01995,0.0098
cLn part,wMat,0.01995,0.0098,0.01975,0.01
cLn part,wMat,0.01975,0.01,0.01925,0.01
cLn part,wMat,0.01925,0.01,0.01925,0.0081
cCLn part,wMat,0.02245,0.006,0.01925,0.006
Part.SketchManager.InsertSketch True
end sub

sub codeBag14(part,wMat)
cLn part,wMat,-0.006,0,0.006,0
cLn part,wMat,0.006,0,0.006,0.012
cLn part,wMat,0.006,0.012,-0.006,0.012
cLn part,wMat,-0.006,0.012,-0.006,0
cArc part,wMat,-0.001,0.0099,-0.0049,0.006,-0.001,0.0021
cLn part,wMat,-0.001,0.0021,0.001,0.0021
cArc part,wMat,0.001,0.0021,0.0049,0.006,0.001,0.0099
cLn part,wMat,0.001,0.0099,-0.001,0.0099
Part.SketchManager.InsertSketch True
end sub

sub codeBag0(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag1 part,wMat
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.01925,0.01925,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag2 part,wMat
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.025,0.025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag3 part,wMat
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.025,0.025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag4 part,wMat
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
featMgr.FeatureRevolveCut2 1.5707963267949,1,1.5707963267949,2,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat12=part.Extension.GetLastFeatureAdded()
feat12.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag5 part,wMat
set feat12=part.Extension.GetLastFeatureAdded()
feat12.select2 false,0
featMgr.FeatureRevolveCut2 1.5707963267949,1,1.5707963267949,2,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat14=part.Extension.GetLastFeatureAdded()
feat14.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag6 part,wMat
set feat14=part.Extension.GetLastFeatureAdded()
feat14.select2 false,0
featMgr.FeatureRevolveCut2 0.78539816339745,1,0.78539816339745,2,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag7 part,wMat
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
featMgr.FeatureRevolveCut2 0.78539816339745,1,0.78539816339745,2,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(-0.0137,0,0),createVec3d(-0.0137,0,-1),createVec3d(-0.0137,1,0),1
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.0137,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag8 part,wMat
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.0053,0.0053,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(-0.0137,0,0),createVec3d(-0.0137,0,-1),createVec3d(-0.0137,1,0),1
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.0137,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag9 part,wMat
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.0053,0.0053,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0.0137,0,0),createVec3d(0.0137,0,-1),createVec3d(0.0137,1,0),1
set feat24=part.Extension.GetLastFeatureAdded()
feat24.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.0137,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag10 part,wMat
set feat24=part.Extension.GetLastFeatureAdded()
feat24.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.0053,0.0053,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0.0137,0,0),createVec3d(0.0137,0,-1),createVec3d(0.0137,1,0),1
set feat26=part.Extension.GetLastFeatureAdded()
feat26.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.0137,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag11 part,wMat
set feat26=part.Extension.GetLastFeatureAdded()
feat26.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.0053,0.0053,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat28=part.Extension.GetLastFeatureAdded()
feat28.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag12 part,wMat
set feat28=part.Extension.GetLastFeatureAdded()
feat28.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.00155,0.00155,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat30=part.Extension.GetLastFeatureAdded()
feat30.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag13 part,wMat
set feat30=part.Extension.GetLastFeatureAdded()
feat30.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0.02245,0,0),createVec3d(0.02245,0,-1),createVec3d(0.02245,1,0),1
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.02245,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag14 part,wMat
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.002,0.002,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
end sub

sub codeBag16(part,wMat)
cArc part,wMat,-0.022445513270952,0.0085816904893691,-0.022395843330161,0.0083580667076584,-0.022202833892775,0.0082346890117618
cLn part,wMat,-0.022202833892775,0.0082346890117618,-0.02145,0.0081
cLn part,wMat,-0.02145,0.0081,-0.01925,0.0081
cLn part,wMat,-0.01925,0.0081,-0.01925,0.01
cLn part,wMat,-0.01925,0.01,-0.01975,0.01
cLn part,wMat,-0.01975,0.01,-0.01995,0.0098
cLn part,wMat,-0.01995,0.0098,-0.01995,0.0086
cLn part,wMat,-0.01995,0.0086,-0.02065,0.0086
cLn part,wMat,-0.02065,0.0086,-0.02065,0.0109
cLn part,wMat,-0.02065,0.0109,-0.02204,0.0109
cLn part,wMat,-0.02204,0.0109,-0.022445513270952,0.0085816904893691
cCLn part,wMat,-0.01925,0.006,-0.02245,0.006
Part.SketchManager.InsertSketch True
end sub

sub codeBag17(part,wMat)
cLn part,wMat,-0.006,0,0.006,0
cLn part,wMat,0.006,0,0.006,0.012
cLn part,wMat,0.006,0.012,-0.006,0.012
cLn part,wMat,-0.006,0.012,-0.006,0
cArc part,wMat,-0.001,0.0099,-0.0049,0.006,-0.001,0.0021
cLn part,wMat,-0.001,0.0021,0.001,0.0021
cArc part,wMat,0.001,0.0021,0.0049,0.006,0.001,0.0099
cLn part,wMat,0.001,0.0099,-0.001,0.0099
Part.SketchManager.InsertSketch True
end sub

sub codeBag18(part,wMat)
cLn part,wMat,-0.004,-0.008,-0.004,-0.0085
cArc part,wMat,-0.004,-0.0085,-2.5409873630716e-18,-0.009,0.004,-0.0085
cLn part,wMat,0.004,-0.0085,0.004,-0.008
cLn part,wMat,0.004,-0.008,-0.004,-0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag19(part,wMat)
cLn part,wMat,-0.004,0.008,0.004,0.008
cLn part,wMat,0.004,0.008,0.004,0.0085
cArc part,wMat,0.004,0.0085,5.5093631445716e-19,0.009,-0.004,0.0085
cLn part,wMat,-0.004,0.0085,-0.004,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag20(part,wMat)
cLn part,wMat,-0.008,0.027,-0.00655,0.027
cLn part,wMat,-0.00655,0.027,-0.00655,0.022
cLn part,wMat,-0.00655,0.022,-0.008,0.022
cLn part,wMat,-0.008,0.022,-0.008,0.027
cCLn part,wMat,-0.008,0.022,-0.008,0.027
Part.SketchManager.InsertSketch True
end sub

sub codeBag21(part,wMat)
cArc part,wMat,-0.008,0.0243,-0.0074984281550471,0.024334281550471,-0.007,0.0244
cLn part,wMat,-0.007,0.0244,-0.0068,0.0244
cArc part,wMat,-0.0068,0.0244,-0.0066585786437627,0.024341421356237,-0.0066,0.0242
cLn part,wMat,-0.0066,0.0242,-0.0066,0.022
cLn part,wMat,-0.0066,0.022,-0.008,0.022
cLn part,wMat,-0.008,0.022,-0.008,0.0243
cCLn part,wMat,-0.008,0.022,-0.008,0.0243
Part.SketchManager.InsertSketch True
end sub

sub codeBag22(part,wMat)
cLn part,wMat,0.01925,0.018,0.01925,0.021537788323986
cLn part,wMat,0.01925,0.021537788323986,0.0218720944533,0.021075442325904
cArc part,wMat,0.0218720944533,0.021075442325904,0.022032132034356,0.020992132034356,0.022115442325904,0.0208320944533
cLn part,wMat,0.022115442325904,0.0208320944533,0.02225,0.020068979962507
cLn part,wMat,0.02225,0.020068979962507,0.02225,0.01945
cLn part,wMat,0.02225,0.01945,0.02945,0.01945
cLn part,wMat,0.02945,0.01945,0.02945,0.018
cLn part,wMat,0.02945,0.018,0.01925,0.018
cCLn part,wMat,0.02945,0.018,0.01925,0.018
Part.SketchManager.InsertSketch True
end sub

sub codeBag23(part,wMat)
cArc part,wMat,-5.5511151231258e-20,0.018406155281281,-0.00077783785074528,0.018444414726529,-0.0004240363981417,0.017750642401239
cArc part,wMat,-0.0004240363981417,0.017750642401239,-6.5821781464483e-19,0.01715,0.0004240363981417,0.017750642401239
cArc part,wMat,0.0004240363981417,0.017750642401239,0.00077783785074528,0.018444414726529,-5.5511151231258e-20,0.018406155281281
Part.SketchManager.InsertSketch True
end sub

sub codeBag24(part,wMat)
cArc part,wMat,0,0.018132287565553,-0.00032049310292724,0.018104556692059,-0.00019989995996797,0.017806325030024
cArc part,wMat,-0.00019989995996797,0.017806325030024,-3.6739403974421e-20,0.0176,0.00019989995996797,0.017806325030024
cArc part,wMat,0.00019989995996797,0.017806325030024,0.00032049310292724,0.018104556692059,0,0.018132287565553
Part.SketchManager.InsertSketch True
end sub

sub codeBag15(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag16 part,wMat
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(-0.02245,0,0),createVec3d(-0.02245,0,-1),createVec3d(-0.02245,1,0),1
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.02245,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag17 part,wMat
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.002,0.002,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.017,0),createVec3d(1,0.017,0),createVec3d(0,0.017,-1),1
set feat43=part.Extension.GetLastFeatureAdded()
feat43.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.017,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag18 part,wMat
set feat43=part.Extension.GetLastFeatureAdded()
feat43.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.017,0),createVec3d(1,0.017,0),createVec3d(0,0.017,-1),1
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.017,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag19 part,wMat
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0.0023),createVec3d(1,0,0.0023),createVec3d(0,1,0.0023),1
set feat50=part.Extension.GetLastFeatureAdded()
feat50.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0.0023)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag20 part,wMat
set feat50=part.Extension.GetLastFeatureAdded()
feat50.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,0.0023),createVec3d(1,0,0.0023),createVec3d(0,1,0.0023),1
set feat52=part.Extension.GetLastFeatureAdded()
feat52.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0.0023)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag21 part,wMat
set feat52=part.Extension.GetLastFeatureAdded()
feat52.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag22 part,wMat
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0.03925,0,0),createVec3d(0.03925,0,-1),createVec3d(0.03925,1,0),1
set feat57=part.Extension.GetLastFeatureAdded()
feat57.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.03925,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag23 part,wMat
set feat57=part.Extension.GetLastFeatureAdded()
feat57.select2 false,0
featMgr.FeatureExtrusion2 1,0,1,0,0,0.0098,0.0098,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0.03925,0,0),createVec3d(0.03925,0,-1),createVec3d(0.03925,1,0),1
set feat59=part.Extension.GetLastFeatureAdded()
feat59.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.03925,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag24 part,wMat
set feat59=part.Extension.GetLastFeatureAdded()
feat59.select2 false,0
featMgr.FeatureExtrusion2 1,0,0,0,0,0.003,0.003,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
end sub

sub codeBag26(part,wMat)
cLn part,wMat,-0.013,0.0041041451884327,-0.013,0.0012958548115673
cArc part,wMat,-0.013,0.0012958548115673,-0.01285,0.0010360471904319,-0.01255,0.0010360471904319
cLn part,wMat,-0.01255,0.0010360471904319,-0.0117,0.0015267949192431
cArc part,wMat,-0.0117,0.0015267949192431,-0.0115,0.0015267949192431,-0.0114,0.0013535898384862
cLn part,wMat,-0.0114,0.0013535898384862,-0.0114,0
cLn part,wMat,-0.0114,0,0.01,0
cLn part,wMat,0.01,0,0.01,0.0010803847577293
cArc part,wMat,0.01,0.0010803847577293,0.00985,0.0013401923788647,0.00955,0.0013401923788647
cLn part,wMat,0.00955,0.0013401923788647,0.0089,0.00096491470389141
cArc part,wMat,0.0089,0.00096491470389141,0.0085,0.00096491470389141,0.0083,0.0013113248654052
cLn part,wMat,0.0083,0.0013113248654052,0.0083,0.0040886751345948
cArc part,wMat,0.0083,0.0040886751345948,0.0085,0.0044350852961086,0.0089,0.0044350852961086
cLn part,wMat,0.0089,0.0044350852961086,0.00955,0.0040598076211353
cArc part,wMat,0.00955,0.0040598076211353,0.00985,0.0040598076211353,0.01,0.0043196152422707
cLn part,wMat,0.01,0.0043196152422707,0.01,0.0236
cArc part,wMat,0.01,0.0236,0.0098828427124746,0.023882842712475,0.0096,0.024
cLn part,wMat,0.0096,0.024,0.0084,0.024
cArc part,wMat,0.0084,0.024,0.0081171572875254,0.023882842712475,0.008,0.0236
cLn part,wMat,0.008,0.0236,0.008,0.014
cArc part,wMat,0.008,0.014,-1.4695761589768e-18,0.006,-0.008,0.014
cLn part,wMat,-0.008,0.014,-0.008,0.0236
cArc part,wMat,-0.008,0.0236,-0.0081171572875254,0.023882842712475,-0.0084,0.024
cLn part,wMat,-0.0084,0.024,-0.0096,0.024
cArc part,wMat,-0.0096,0.024,-0.0098828427124746,0.023882842712475,-0.01,0.0236
cLn part,wMat,-0.01,0.0236,-0.01,0.0054
cLn part,wMat,-0.01,0.0054,-0.0114,0.0054
cLn part,wMat,-0.0114,0.0054,-0.0114,0.0040464101615138
cArc part,wMat,-0.0114,0.0040464101615138,-0.0115,0.0038732050807569,-0.0117,0.0038732050807569
cLn part,wMat,-0.0117,0.0038732050807569,-0.01255,0.0043639528095681
cArc part,wMat,-0.01255,0.0043639528095681,-0.01285,0.0043639528095681,-0.013,0.0041041451884327
Part.SketchManager.InsertSketch True
end sub

sub codeBag27(part,wMat)
cLn part,wMat,-0.007,0.033,-0.007,0.008
cLn part,wMat,-0.007,0.008,0.007,0.008
cLn part,wMat,0.007,0.008,0.007,0.033
cLn part,wMat,0.007,0.033,-0.007,0.033
Part.SketchManager.InsertSketch True
end sub

sub codeBag28(part,wMat)
cLn part,wMat,0.008,0.028563897926375,0.008,0.008
cLn part,wMat,0.008,0.008,0.01,0.008
cLn part,wMat,0.01,0.008,0.01,0.027401851761137
cArc part,wMat,0.01,0.027401851761137,0.0099409199540865,0.027611073138882,0.0097811321103074,0.027758490455919
cArc part,wMat,0.0097811321103074,0.027758490455919,0.008899681722544,0.028181353236945,0.008,0.028563897926375
Part.SketchManager.InsertSketch True
end sub

sub codeBag29(part,wMat)
cLn part,wMat,-0.01,0.027401851761137,-0.01,0.008
cLn part,wMat,-0.01,0.008,-0.008,0.008
cLn part,wMat,-0.008,0.008,-0.008,0.028563897926375
cArc part,wMat,-0.008,0.028563897926375,-0.008899681722544,0.028181353236945,-0.0097811320754717,0.027758490473611
cArc part,wMat,-0.0097811320754717,0.027758490473611,-0.0099409199540865,0.027611073138882,-0.01,0.027401851761137
Part.SketchManager.InsertSketch True
end sub

sub codeBag30(part,wMat)
cLn part,wMat,-0.0035,0.01,-0.0035,0.008
cLn part,wMat,-0.0035,0.008,0.0035,0.008
cLn part,wMat,0.0035,0.008,0.0035,0.01
cLn part,wMat,0.0035,0.01,-0.0035,0.01
Part.SketchManager.InsertSketch True
end sub

sub codeBag31(part,wMat)
cLn part,wMat,-0.0124,0.019,-0.0124,0.0209
cArc part,wMat,-0.0124,0.0209,-0.012253553390593,0.021253553390593,-0.0119,0.0214
cLn part,wMat,-0.0119,0.0214,-0.01,0.0214
cLn part,wMat,-0.01,0.0214,-0.01,0.019
cLn part,wMat,-0.01,0.019,-0.0124,0.019
cCLn part,wMat,-0.01,0.019,-0.0124,0.019
Part.SketchManager.InsertSketch True
end sub

sub codeBag32(part,wMat)
cLn part,wMat,0.008,0.019,0.008,0.0215
cLn part,wMat,0.008,0.0215,0.0095,0.0215
cLn part,wMat,0.0095,0.0215,0.01,0.022
cLn part,wMat,0.01,0.022,0.01,0.019
cLn part,wMat,0.01,0.019,0.008,0.019
cCLn part,wMat,0.01,0.019,0.008,0.019
Part.SketchManager.InsertSketch True
end sub

sub codeBag33(part,wMat)
cLn part,wMat,0.0072,0.020799444650053,0.0072,0.019200555349947
cArc part,wMat,0.0072,0.019200555349947,0.0072669872981078,0.018950555349947,0.00745,0.018767542648054
cLn part,wMat,0.00745,0.018767542648054,0.00775,0.018594337567297
cArc part,wMat,0.00775,0.018594337567297,0.0079330127018922,0.018411324865405,0.008,0.018161324865405
cLn part,wMat,0.008,0.018161324865405,0.008,0.021838675134595
cArc part,wMat,0.008,0.021838675134595,0.0079330127018922,0.021588675134595,0.00775,0.021405662432703
cLn part,wMat,0.00775,0.021405662432703,0.00745,0.021232457351946
cArc part,wMat,0.00745,0.021232457351946,0.0072669872981078,0.021049444650053,0.0072,0.020799444650053
Part.SketchManager.InsertSketch True
end sub

sub codeBag34(part,wMat)
cArc part,wMat,-0.008,0.018161324865405,-0.0079330127018922,0.018411324865405,-0.00775,0.018594337567297
cLn part,wMat,-0.00775,0.018594337567297,-0.00745,0.018767542648054
cArc part,wMat,-0.00745,0.018767542648054,-0.0072669872981078,0.018950555349946,-0.0072,0.019200555349946
cLn part,wMat,-0.0072,0.019200555349946,-0.0072,0.020799444650053
cArc part,wMat,-0.0072,0.020799444650053,-0.0072669872981078,0.021049444650054,-0.00745,0.021232457351946
cLn part,wMat,-0.00745,0.021232457351946,-0.00775,0.021405662432703
cArc part,wMat,-0.00775,0.021405662432703,-0.0079330127018922,0.021588675134595,-0.008,0.021838675134595
cLn part,wMat,-0.008,0.021838675134595,-0.008,0.018161324865405
Part.SketchManager.InsertSketch True
end sub

sub codeBag35(part,wMat)
cLn part,wMat,0.0072,0.020799444650053,0.0072,0.019200555349947
cArc part,wMat,0.0072,0.019200555349947,0.0072669872981078,0.018950555349947,0.00745,0.018767542648054
cLn part,wMat,0.00745,0.018767542648054,0.00775,0.018594337567297
cArc part,wMat,0.00775,0.018594337567297,0.0079330127018922,0.018411324865405,0.008,0.018161324865405
cLn part,wMat,0.008,0.018161324865405,0.008,0.021838675134595
cArc part,wMat,0.008,0.021838675134595,0.0079330127018922,0.021588675134595,0.00775,0.021405662432703
cLn part,wMat,0.00775,0.021405662432703,0.00745,0.021232457351946
cArc part,wMat,0.00745,0.021232457351946,0.0072669872981078,0.021049444650053,0.0072,0.020799444650053
Part.SketchManager.InsertSketch True
end sub

sub codeBag36(part,wMat)
cArc part,wMat,-0.008,0.018161324865405,-0.0079330127018922,0.018411324865405,-0.00775,0.018594337567297
cLn part,wMat,-0.00775,0.018594337567297,-0.00745,0.018767542648054
cArc part,wMat,-0.00745,0.018767542648054,-0.0072669872981078,0.018950555349946,-0.0072,0.019200555349946
cLn part,wMat,-0.0072,0.019200555349946,-0.0072,0.020799444650053
cArc part,wMat,-0.0072,0.020799444650053,-0.0072669872981078,0.021049444650054,-0.00745,0.021232457351946
cLn part,wMat,-0.00745,0.021232457351946,-0.00775,0.021405662432703
cArc part,wMat,-0.00775,0.021405662432703,-0.0079330127018922,0.021588675134595,-0.008,0.021838675134595
cLn part,wMat,-0.008,0.021838675134595,-0.008,0.018161324865405
Part.SketchManager.InsertSketch True
end sub

sub codeBag37(part,wMat)
cArc part,wMat,0.0095,0.005,0.0045,4.1650370783742e-18,0.0095,-0.005
cLn part,wMat,0.0095,-0.005,0.0105,-0.005
cArc part,wMat,0.0105,-0.005,0.013,-0.0043301270189222,0.014830127018922,-0.0025
cLn part,wMat,0.014830127018922,-0.0025,0.01925,-0.0025
cLn part,wMat,0.01925,-0.0025,0.01925,0.0025
cLn part,wMat,0.01925,0.0025,0.014830127018922,0.0025
cArc part,wMat,0.014830127018922,0.0025,0.013,0.0043301270189222,0.0105,0.005
cLn part,wMat,0.0105,0.005,0.0095,0.005
Part.SketchManager.InsertSketch True
end sub

sub codeBag38(part,wMat)
cLn part,wMat,-0.01925,-0.0025,-0.014582575694956,-0.0025
cArc part,wMat,-0.014582575694956,-0.0025,-0.0089784517815539,-0.0053945315646535,-0.005,-0.0005
cLn part,wMat,-0.005,-0.0005,-0.005,0.0005
cArc part,wMat,-0.005,0.0005,-0.0089784517815539,0.0053945315646535,-0.014582575694956,0.0025
cLn part,wMat,-0.014582575694956,0.0025,-0.01925,0.0025
cLn part,wMat,-0.01925,0.0025,-0.01925,-0.0025
Part.SketchManager.InsertSketch True
end sub

sub codeBag39(part,wMat)
cLn part,wMat,0.00825,0.008,0.00825,0.005
cLn part,wMat,0.00825,0.005,0.01375,0.005
cLn part,wMat,0.01375,0.005,0.01375,0.008
cArc part,wMat,0.01375,0.008,0.013222976481598,0.0074701440044768,0.012526181402837,0.0072
cLn part,wMat,0.012526181402837,0.0072,0.0094738185971633,0.0072
cArc part,wMat,0.0094738185971633,0.0072,0.0087770235184021,0.0074701440044768,0.00825,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag25(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag26 part,wMat
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.01925,0.01925,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag27 part,wMat
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.012,0.012,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag28 part,wMat
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.005,0.005,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag29 part,wMat
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
featMgr.FeatureExtrusion2 0,0,1,0,0,0.005,0.005,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat12=part.Extension.GetLastFeatureAdded()
feat12.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag30 part,wMat
set feat12=part.Extension.GetLastFeatureAdded()
feat12.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.012,0.012,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat14=part.Extension.GetLastFeatureAdded()
feat14.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag31 part,wMat
set feat14=part.Extension.GetLastFeatureAdded()
feat14.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag32 part,wMat
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0.00825,0,0),createVec3d(0.00825,0,-1),createVec3d(0.00825,1,0),1
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.00825,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag33 part,wMat
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
featMgr.FeatureExtrusion2 1,0,0,0,0,0.0055,0.0055,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0.00825,0,0),createVec3d(0.00825,0,-1),createVec3d(0.00825,1,0),1
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.00825,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag34 part,wMat
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
featMgr.FeatureExtrusion2 1,0,0,0,0,0.0055,0.0055,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(-0.00825,0,0),createVec3d(-0.00825,0,-1),createVec3d(-0.00825,1,0),1
set feat24=part.Extension.GetLastFeatureAdded()
feat24.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.00825,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag35 part,wMat
set feat24=part.Extension.GetLastFeatureAdded()
feat24.select2 false,0
featMgr.FeatureExtrusion2 1,0,1,0,0,0.0055,0.0055,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(-0.00825,0,0),createVec3d(-0.00825,0,-1),createVec3d(-0.00825,1,0),1
set feat26=part.Extension.GetLastFeatureAdded()
feat26.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.00825,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag36 part,wMat
set feat26=part.Extension.GetLastFeatureAdded()
feat26.select2 false,0
featMgr.FeatureExtrusion2 1,0,1,0,0,0.0055,0.0055,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.003,0),createVec3d(1,0.003,0),createVec3d(0,0.003,-1),1
set feat29=part.Extension.GetLastFeatureAdded()
feat29.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.003,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag37 part,wMat
set feat29=part.Extension.GetLastFeatureAdded()
feat29.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.007,0.007,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.003,0),createVec3d(1,0.003,0),createVec3d(0,0.003,-1),1
set feat31=part.Extension.GetLastFeatureAdded()
feat31.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.003,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag38 part,wMat
set feat31=part.Extension.GetLastFeatureAdded()
feat31.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.007,0.007,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.02,0),createVec3d(1,0.02,0),createVec3d(0,0.02,-1),1
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.02,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag39 part,wMat
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.0025,0.0025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
end sub

sub codeBag41(part,wMat)
cLn part,wMat,-0.01375,0.008,-0.01375,0.005
cLn part,wMat,-0.01375,0.005,-0.00825,0.005
cLn part,wMat,-0.00825,0.005,-0.00825,0.008
cArc part,wMat,-0.00825,0.008,-0.0087770235184021,0.0074701440044768,-0.0094738185971633,0.0072
cLn part,wMat,-0.0094738185971633,0.0072,-0.012526181402837,0.0072
cArc part,wMat,-0.012526181402837,0.0072,-0.013222976481598,0.0074701440044768,-0.01375,0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag42(part,wMat)
cArc part,wMat,0.00825,-0.008,0.008777023518402,-0.0074701440044768,0.0094738185971633,-0.0072
cLn part,wMat,0.0094738185971633,-0.0072,0.012526181402837,-0.0072
cArc part,wMat,0.012526181402837,-0.0072,0.013222976481598,-0.0074701440044768,0.01375,-0.008
cLn part,wMat,0.01375,-0.008,0.01375,-0.005
cLn part,wMat,0.01375,-0.005,0.00825,-0.005
cLn part,wMat,0.00825,-0.005,0.00825,-0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag43(part,wMat)
cArc part,wMat,-0.01375,-0.008,-0.013222976481598,-0.0074701440044768,-0.012526181402837,-0.0072
cLn part,wMat,-0.012526181402837,-0.0072,-0.0094738185971633,-0.0072
cArc part,wMat,-0.0094738185971633,-0.0072,-0.0087770235184021,-0.0074701440044768,-0.00825,-0.008
cLn part,wMat,-0.00825,-0.008,-0.00825,-0.005
cLn part,wMat,-0.00825,-0.005,-0.01375,-0.005
cLn part,wMat,-0.01375,-0.005,-0.01375,-0.008
Part.SketchManager.InsertSketch True
end sub

sub codeBag44(part,wMat)
cLn part,wMat,-0.01825,0.0068,-0.01825,-0.0085
cLn part,wMat,-0.01825,-0.0085,0.01825,-0.0085
cLn part,wMat,0.01825,-0.0085,0.01825,0.0068
cLn part,wMat,0.01825,0.0068,-0.01825,0.0068
Part.SketchManager.InsertSketch True
end sub

sub codeBag45(part,wMat)
cLn part,wMat,-0.004675,0.008178190867597,-0.004675,-0.008178190867597
cArc part,wMat,-0.004675,-0.008178190867597,-0.0046021220996745,-0.008374189724327,-0.0044188963210702,-0.0084749620134258
cArc part,wMat,-0.0044188963210702,-0.0084749620134258,-8.8878486432934e-18,-0.0088,0.0044188963210702,-0.0084749620134258
cArc part,wMat,0.0044188963210702,-0.0084749620134258,0.0046021220996745,-0.008374189724327,0.004675,-0.008178190867597
cLn part,wMat,0.004675,-0.008178190867597,0.004675,0.008178190867597
cArc part,wMat,0.004675,0.008178190867597,0.0046021220996745,0.008374189724327,0.0044188963210702,0.0084749620134258
cArc part,wMat,0.0044188963210702,0.0084749620134258,5.1894153098684e-18,0.0088,-0.0044188963210702,0.0084749620134258
cArc part,wMat,-0.0044188963210702,0.0084749620134258,-0.0046021220996745,0.008374189724327,-0.004675,0.008178190867597
Part.SketchManager.InsertSketch True
end sub

sub codeBag46(part,wMat)
cLn part,wMat,-0.002125,-0.0087,0.002125,-0.0087
cLn part,wMat,0.002125,-0.0087,0.002125,0.0087
cLn part,wMat,0.002125,0.0087,-0.002125,0.0087
cLn part,wMat,-0.002125,0.0087,-0.002125,-0.0087
Part.SketchManager.InsertSketch True
end sub

sub codeBag47(part,wMat)
cArc part,wMat,-0.002125,-0.00525,-0.0018321067811865,-0.0059571067811865,-0.001125,-0.00625
cLn part,wMat,-0.001125,-0.00625,0.001125,-0.00625
cArc part,wMat,0.001125,-0.00625,0.0018321067811865,-0.0059571067811865,0.002125,-0.00525
cLn part,wMat,0.002125,-0.00525,0.002125,0.00525
cArc part,wMat,0.002125,0.00525,0.0018321067811865,0.0059571067811865,0.001125,0.00625
cLn part,wMat,0.001125,0.00625,-0.001125,0.00625
cArc part,wMat,-0.001125,0.00625,-0.0018321067811865,0.0059571067811865,-0.002125,0.00525
cLn part,wMat,-0.002125,0.00525,-0.002125,-0.00525
Part.SketchManager.InsertSketch True
end sub

sub codeBag48(part,wMat)
cArc part,wMat,0.0095,0.00225,0.00725,2.7554552980815e-19,0.0095,-0.00225
cLn part,wMat,0.0095,-0.00225,0.0105,-0.00225
cArc part,wMat,0.0105,-0.00225,0.01275,-5.5109105961631e-19,0.0105,0.00225
cLn part,wMat,0.0105,0.00225,0.0095,0.00225
Part.SketchManager.InsertSketch True
end sub

sub codeBag49(part,wMat)
cArc part,wMat,0.0095,0.00375,0.00575,4.5924254968026e-19,0.0095,-0.00375
cLn part,wMat,0.0095,-0.00375,0.0105,-0.00375
cArc part,wMat,0.0105,-0.00375,0.01425,-9.1848509936051e-19,0.0105,0.00375
cLn part,wMat,0.0105,0.00375,0.0095,0.00375
cArc part,wMat,0.0095,0.00225,0.00725,2.7554552980815e-19,0.0095,-0.00225
cLn part,wMat,0.0095,-0.00225,0.0105,-0.00225
cArc part,wMat,0.0105,-0.00225,0.01275,-5.5109105961631e-19,0.0105,0.00225
cLn part,wMat,0.0105,0.00225,0.0095,0.00225
Part.SketchManager.InsertSketch True
end sub

sub codeBag50(part,wMat)
cLn part,wMat,-0.01225,0.0005,-0.01225,-0.0005
cArc part,wMat,-0.01225,-0.0005,-0.01,-0.00275,-0.00775,-0.0005
cLn part,wMat,-0.00775,-0.0005,-0.00775,0.0005
cArc part,wMat,-0.00775,0.0005,-0.01,0.00275,-0.01225,0.0005
Part.SketchManager.InsertSketch True
end sub

sub codeBag51(part,wMat)
cArc part,wMat,-0.01375,-0.0005,-0.01,-0.00425,-0.00625,-0.0005
cLn part,wMat,-0.00625,-0.0005,-0.00625,0.0005
cArc part,wMat,-0.00625,0.0005,-0.01,0.00425,-0.01375,0.0005
cLn part,wMat,-0.01375,0.0005,-0.01375,-0.0005
cArc part,wMat,-0.01225,-0.0005,-0.01,-0.00275,-0.00775,-0.0005
cLn part,wMat,-0.00775,-0.0005,-0.00775,0.0005
cArc part,wMat,-0.00775,0.0005,-0.01,0.00275,-0.01225,0.0005
cLn part,wMat,-0.01225,0.0005,-0.01225,-0.0005
Part.SketchManager.InsertSketch True
end sub

sub codeBag40(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0.02,0),createVec3d(1,0.02,0),createVec3d(0,0.02,-1),1
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.02,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag41 part,wMat
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.0025,0.0025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.02,0),createVec3d(1,0.02,0),createVec3d(0,0.02,-1),1
set feat38=part.Extension.GetLastFeatureAdded()
feat38.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.02,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag42 part,wMat
set feat38=part.Extension.GetLastFeatureAdded()
feat38.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.0025,0.0025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.02,0),createVec3d(1,0.02,0),createVec3d(0,0.02,-1),1
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.02,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag43 part,wMat
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.0025,0.0025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat42=part.Extension.GetLastFeatureAdded()
feat42.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag44 part,wMat
set feat42=part.Extension.GetLastFeatureAdded()
feat42.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.0015,0.0015,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.0171,0),createVec3d(1,0.0171,0),createVec3d(0,0.0171,-1),1
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0171,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag45 part,wMat
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.015,0.015,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.0171,0),createVec3d(1,0.0171,0),createVec3d(0,0.0171,-1),1
set feat47=part.Extension.GetLastFeatureAdded()
feat47.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0171,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag46 part,wMat
set feat47=part.Extension.GetLastFeatureAdded()
feat47.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.008,0.008,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0.005,0),createVec3d(1,0.005,0),createVec3d(0,0.005,-1),1
set feat50=part.Extension.GetLastFeatureAdded()
feat50.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.005,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag47 part,wMat
set feat50=part.Extension.GetLastFeatureAdded()
feat50.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.007,0.007,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat52=part.Extension.GetLastFeatureAdded()
feat52.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag48 part,wMat
set feat52=part.Extension.GetLastFeatureAdded()
feat52.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.007,0.007,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag49 part,wMat
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
featMgr.FeatureExtrusion2 1,0,0,0,0,0.0015,0.0015,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat56=part.Extension.GetLastFeatureAdded()
feat56.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag50 part,wMat
set feat56=part.Extension.GetLastFeatureAdded()
feat56.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat58=part.Extension.GetLastFeatureAdded()
feat58.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag51 part,wMat
set feat58=part.Extension.GetLastFeatureAdded()
feat58.select2 false,0
featMgr.FeatureExtrusion2 1,0,0,0,0,0.0015,0.0015,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
end sub

sub main
set swApp = Application.SldWorks
code = swApp.RevisionNumber
found = InStr(code, ".")
If (found > 0) Then
  code = Left(code, found-1)
  docVisible=1
  If (CInt(code) >= 18) Then
    docVisible=0
  End If
End If
swApp.SetUserPreferenceToggle 11, FALSE
swApp.SetUserPreferenceToggle 97, FALSE
storePath=BrowseForFolder
If (storePath <> "") Then
   If ((Right(storePath, 1) <> "\") And (Right(storePath, 1) <> "/")) Then
       storePath = storePath + "\"
   End If
   createPart2
End If
end sub
