' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/27/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "AARL_QR-Quadruped.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Part.SetPickMode

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "AARL_QR-Quadruped.SLDASM"

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Quadruped_Robot\CAD_Mechanical\AARL_QR-Quadruped\InProgress\Cody\AARL_QR-Quadruped.SLDASM", 2, 192, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
swApp.ActivateDoc2 "AARL_QR-Quadruped.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04466952054322997218, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05841398840268535037, 0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06528622233241303252, -0.03849092516066849462
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03849092516066849462
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.05493566746491751474, 0.006090671352382059922, 0.1123066658928451034, -0.6512753203953351999, -0.2909754716004553932, -0.7008378785217350693, 0.0005968944703641735489, 2, False, 0, 0)
Part.OpenCompFile

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Quadruped_Robot\CAD_Mechanical\AARL_QR-Quadruped\AARL_QR_PN-Pneumatics\AARL_QR_PN_EP-End_Pieces\Completed\AARL_QR_PN_EP_001.SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "AARL_QR_PN_EP_001.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("#10-32 Tapped Hole1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.004566908800143210101, -0.007095160341158646133, 0.001835221073690718185, -0.9546213116693530454, 0.1157454818196354679, 0.2744105222928314713, 0.0001948435007523613069, 2, True, 0, 0)
Part.SetPickMode
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.3849092516066849878
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.07698185032133698924
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06928366528920329448
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04618911019280220326
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03849092516066849462
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.06158548025706959278
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04618911019280220326
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.08468003535347069788
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03849092516066849462
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007698185032133699097
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.03079274012853479639
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02309455509640110163
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01539637006426739819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
